### ISSUE TITLE
Bug: AttributeError: 'Expr' object has no attribute 'end_lineno'

### ISSUE THREAD

**Issue by ClaudioSalvatoreArcidiacono** [ClaudioSalvatoreArcidiacono/docmat#3]
# Input code

```python
class Anyclass:
    def __init__(self):
        """Class constructor.
        """
        pass
```

# Expected

```python
class Anyclass:
    def __init__(self):
        """Class constructor."""
        pass
```

# Actual

Nothing happens and this is printed to the terminal:

```bash
docmat 'test.py'
Traceback (most recent call last):
  File ".venv/bin/docmat", line 8, in <module>
    sys.exit(main())
  File ".venv/lib/python3.7/site-packages/docmat/__main__.py", line 54, in main
    format_file(file, line_length)
  File ".venv/lib/python3.7/site-packages/docmat/__main__.py", line 36, in format_file
    for offset, docstring_lines in handler.iter_doc():
  File ".venv/lib/python3.7/site-packages/docmat/file.py", line 38, in iter_doc
    return list(recurse_yield(ast.parse(self._initial_file_content)))
  File ".venv/lib/python3.7/site-packages/docmat/file.py", line 36, in recurse_yield
    yield from recurse_yield(sub_element)
  File ".venv/lib/python3.7/site-packages/docmat/file.py", line 36, in recurse_yield
    yield from recurse_yield(sub_element)
  File ".venv/lib/python3.7/site-packages/docmat/file.py", line 27, in recurse_yield
    end = expression.end_lineno
AttributeError: 'Expr' object has no attribute 'end_lineno'
```

**Comment by ClaudioSalvatoreArcidiacono** [comment]
Apparently the end_lineno attribute of ast elements was not available in version 3.7:
https://docs.python.org/3.7/library/ast.html
